### ISSUE TITLE
Magento2 module architecture

### ISSUE THREAD

**Issue by Coderimus** [magento-notes/magento2-exam-notes#1]
Please, describe general Magento 2 module architecture. As a plan for this, I can suggest using [Components](http://devdocs.magento.com/guides/v2.2/architecture/archi_perspectives/components/AComponents.html) section from the official M2 documentation:

1. Module overview
2. Modules and areas
3. Module conventions
4. Module relationships
5. Module dependencies
6. Module dependency types

**Comment by simpleadm** [comment]
https://github.com/magento-notes/magento2-exam-notes/blob/master/1.%20Magento%20Architecture%20and%20Customization%20Techniques/1.%20Describe%20Magento%E2%80%99s%20module-based%20architecture.md
