### ISSUE TITLE
Magento configuration files

### ISSUE THREAD

**Issue by Coderimus** [magento-notes/magento2-exam-notes#2]
Please, describe Magento 2 configuration files. It will be good to highlight next sections:
1. Magento’s deployment configuration
2. Module configuration files
3. Create or extend configuration types

Link to the official resource: [Magento configuration files](http://devdocs.magento.com/guides/v2.2/config-guide/config/config-magento.html)

**Comment by simpleadm** [comment]
https://github.com/magento-notes/magento2-exam-notes/blob/master/1.%20Magento%20Architecture%20and%20Customization%20Techniques/3.%20Utilize%20configuration%20XML%20and%20variables%20scope.md
