### ISSUE TITLE
Dependency injection design pattern in Magento 2

### ISSUE THREAD

**Issue by Coderimus** [magento-notes/magento2-exam-notes#3]
One of the base thing in Magento 2 is a dependency injection pattern. Please, describe the usage of this pattern in Magento 2 by covering next sections:
1. Injection types
2. di.xml
3. Construction
4. Compiling dependencies

Those 4 steps are optional and can be extended with the new one or completely changed.

**Comment by simpleadm** [comment]
Done: https://github.com/magento-notes/magento2-exam-notes/blob/master/1.%20Magento%20Architecture%20and%20Customization%20Techniques/4.%20Demonstrate%20how%20to%20use%20dependency%20injection.md
